/* ZENA CARDS — 카드 데이터
 * 새 카드 추가법:
 *  1) 생성한 이미지를 이 폴더의 cards/ 에 "카드ID.jpg" 파일명으로 넣는다 (예: cards/XA-N-01.jpg)
 *  2) 아래 목록에서 해당 행의 마지막 숫자를 0 → 1 로 바꾼다 (1 = 게임에 등장)
 *  3) 새 등급/번호 카드는 같은 형식으로 한 줄 추가하면 된다
 * 형식: [카드ID, 표시이름, 등급(N/R/S/SR/SSR), 이미지경로, 사용가능(1/0)]
 */
window.ZENA_CARD_DEFS = [
  /* ── GALLERY EDITION — 기존 화보 (bright-6, dopamine-4/5/6/9 는 대표님 X표시로 제외됨) ── */
  ['GA-AN-01','ANSWER · GALLERY #01','N','../../images/gallery/answer-1.jpg',1],
  ['GA-AN-02','ANSWER · GALLERY #02','N','../../images/gallery/answer-2.jpg',1],
  ['GA-AN-03','ANSWER · GALLERY #03','N','../../images/gallery/answer-3.jpg',1],
  ['GA-AN-04','ANSWER · GALLERY #04','N','../../images/gallery/answer-4.jpg',1],
  ['GA-AN-05','ANSWER · GALLERY #05','N','../../images/gallery/answer-5.jpg',1],
  ['GA-AN-06','ANSWER · GALLERY #06','R','../../images/gallery/answer-6.jpg',1],
  ['GA-AN-07','ANSWER · GALLERY #07','R','../../images/gallery/answer-7.jpg',1],
  ['GA-AN-08','ANSWER · GALLERY #08','R','../../images/gallery/answer-8.jpg',1],
  ['GA-AN-09','ANSWER · GALLERY #09','S','../../images/gallery/answer-9.jpg',1],
  ['GA-AN-10','ANSWER · GALLERY #10','S','../../images/gallery/answer-10.jpg',1],
  ['GA-BR-01','BRIGHT · GALLERY #01','N','../../images/gallery/bright-1.jpg',1],
  ['GA-BR-02','BRIGHT · GALLERY #02','N','../../images/gallery/bright-2.jpg',1],
  ['GA-BR-03','BRIGHT · GALLERY #03','N','../../images/gallery/bright-3.jpg',1],
  ['GA-BR-04','BRIGHT · GALLERY #04','N','../../images/gallery/bright-4.jpg',1],
  ['GA-BR-05','BRIGHT · GALLERY #05','N','../../images/gallery/bright-5.jpg',1],
  ['GA-BR-07','BRIGHT · GALLERY #07','R','../../images/gallery/bright-7.jpg',1],
  ['GA-BR-08','BRIGHT · GALLERY #08','R','../../images/gallery/bright-8.jpg',1],
  ['GA-BR-09','BRIGHT · GALLERY #09','S','../../images/gallery/bright-9.jpg',1],
  ['GA-BR-10','BRIGHT · GALLERY #10','S','../../images/gallery/bright-10.jpg',0], /* 사진 손가락 오류로 영구 제외 */
  ['GA-DP-01','DOPAMINE · GALLERY #01','N','../../images/gallery/dopamine-1.jpg',1],
  ['GA-DP-02','DOPAMINE · GALLERY #02','N','../../images/gallery/dopamine-2.jpg',1],
  ['GA-DP-03','DOPAMINE · GALLERY #03','N','../../images/gallery/dopamine-3.jpg',1],
  ['GA-DP-07','DOPAMINE · GALLERY #07','R','../../images/gallery/dopamine-7.jpg',1],
  ['GA-DP-08','DOPAMINE · GALLERY #08','R','../../images/gallery/dopamine-8.jpg',1],
  ['GA-DP-10','DOPAMINE · GALLERY #10','S','../../images/gallery/dopamine-10.jpg',1],

  /* ── 1ST EDITION — 대표님 확정 등급 반영 (2026-07-18, 65장 활성화) ── */
  /* XENA-A 무대/화보 */
  ['XA-N-03','XENA · CLOSE-UP','N','cards/XA-N-03.jpg',1],
  ['XA-N-05','XENA · NEON ALLEY II','N','cards/XA-N-05.jpg',1],
  ['XA-N-06','XENA · ROOFTOP','N','cards/XA-N-06.jpg',1],
  ['XA-N-07','XENA · GOLDEN SKY','N','cards/XA-N-07.jpg',1],
  ['XA-N-09','XENA · RAIN GLASS','N','cards/XA-N-09.jpg',1],
  ['XA-N-10','XENA · ON STAGE','N','cards/XA-N-10.jpg',1],
  ['XA-R-01','XENA · ALLEY LOW ANGLE','R','cards/XA-R-01.jpg',1],
  ['XA-R-03','XENA · ROOFTOP WIND','R','cards/XA-R-03.jpg',1],
  ['XA-R-04','XENA · GOLDEN HOUR','R','cards/XA-R-04.jpg',1],
  ['XA-R-05','XENA · CRYSTAL CITY','R','cards/XA-R-05.jpg',1],
  ['XA-R-06','XENA · CLUB DANCE','R','cards/XA-R-06.jpg',1],
  ['XA-R-07','XENA · SERVER CORE','R','cards/XA-R-07.jpg',1],
  ['XA-R-08','XENA · RAIN SILHOUETTE','R','cards/XA-R-08.jpg',1],
  ['XA-R-09','XENA · STAGE DANCE','R','cards/XA-R-09.jpg',1],
  ['XA-R-10','XENA · AFTERGLOW','R','cards/XA-R-10.jpg',1],
  ['XA-R-11','XENA · CITY LIGHTS','R','cards/XA-R-11.jpg',1],
  ['XA-R-12','XENA · MIDNIGHT RUN','R','cards/XA-R-12.jpg',1],
  ['XA-R-13','XENA · ENCORE','R','cards/XA-R-13.jpg',1],
  ['XA-S-02','XENA · GOLDEN ASCENT','S','cards/XA-S-02.jpg',1],
  ['XA-S-03','XENA · CRYSTAL DANCE','S','cards/XA-S-03.jpg',1],
  ['XA-S-04','XENA · NEON GAZE','S','cards/XA-S-04.jpg',1],
  ['XA-S-05','XENA · STAGE STORM','S','cards/XA-S-05.jpg',1],
  ['XA-S-06','XENA · ZERO GRAVITY','S','cards/XA-S-06.jpg',1],
  ['XA-S-07','XENA · SPOTLIGHT','S','cards/XA-S-07.jpg',1],
  ['XA-S-08','XENA · LAST TAKE','S','cards/XA-S-08.jpg',1],
  ['XA-SR-01','XENA · CYAN BLADE','SR','cards/XA-SR-01.jpg',1],
  ['XA-SR-02','XENA · ROOFTOP HUNTER','SR','cards/XA-SR-02.jpg',1],
  ['XA-SR-03','XENA · CORE WALKER','SR','cards/XA-SR-03.jpg',1],
  ['XA-SR-04','XENA · SHATTERED TIME','SR','cards/XA-SR-04.jpg',1],
  ['XA-SSR-01','XENA · OVERRIDE','SSR','cards/XA-SSR-01.jpg',1],
  /* XENA-B 스튜디오 */
  ['XB-R-01','XENA · OVER SHOULDER','R','cards/XB-R-01.jpg',1],
  ['XB-R-02','XENA · CONSOLE SEAT','R','cards/XB-R-02.jpg',1],
  ['XB-S-01','XENA · STUDIO GROOVE','S','cards/XB-S-01.jpg',1],
  ['XB-S-03','XENA · BOOTH GLOW','S','cards/XB-S-03.jpg',1],
  ['XB-S-04','XENA · PLAYBACK','S','cards/XB-S-04.jpg',1],
  ['XB-SR-01','XENA · STUDIO SESSION','SR','cards/XB-SR-01.jpg',1],
  ['XB-SR-02','XENA · FIRST TAKE','SR','cards/XB-SR-02.jpg',1],
  ['XB-SR-03','XENA · MIDNIGHT MIX','SR','cards/XB-SR-03.jpg',1],
  ['XB-SSR-01','XENA · STUDIO SELFIE','SSR','cards/XB-SSR-01.jpg',1],
  ['XB-SSR-02','XENA · CHANS THRONE','SSR','cards/XB-SSR-02.jpg',1],
  /* XENA-C 홈 프로듀서 */
  ['XC-N-04','XENA · WINDOW RAIN','N','cards/XC-N-04.jpg',1],
  ['XC-R-03','XENA · RAIN PROFILE','R','cards/XC-R-03.jpg',1],
  ['XC-R-04','XENA · NIGHT WINDOW','R','cards/XC-R-04.jpg',1],
  ['XC-S-01','XENA · QUIET DAWN','S','cards/XC-S-01.jpg',1],
  ['XC-S-02','XENA · GLASS REFLECTION','S','cards/XC-S-02.jpg',1],
  ['XC-S-03','XENA · SOFT STATIC','S','cards/XC-S-03.jpg',1],
  ['XC-S-04','XENA · AFTER HOURS','S','cards/XC-S-04.jpg',1],
  ['XC-SR-01','XENA · HOME AURA','SR','cards/XC-SR-01.jpg',1],
  ['XC-SR-02','XENA · DAWN LIGHT','SR','cards/XC-SR-02.jpg',1],
  ['XC-SR-03','XENA · UNPLUGGED','SR','cards/XC-SR-03.jpg',1],
  /* NIX-09 */
  ['NX-N-02','NIX-09 · ALLEY','N','cards/NX-N-02.jpg',1],
  ['NX-N-03','NIX-09 · SITTING','N','cards/NX-N-03.jpg',1],
  ['NX-N-04','NIX-09 · RAIN WINDOW','N','cards/NX-N-04.jpg',1],
  ['NX-N-05','NIX-09 · MEGACITY','N','cards/NX-N-05.jpg',1],
  ['NX-N-06','NIX-09 · GOLDEN LIGHT','N','cards/NX-N-06.jpg',1],
  ['NX-R-01','NIX-09 · LOOKING BACK','R','cards/NX-R-01.jpg',1],
  ['NX-R-02','NIX-09 · RAIN PROFILE','R','cards/NX-R-02.jpg',1],
  ['NX-R-03','NIX-09 · GOLDEN GAZE','R','cards/NX-R-03.jpg',1],
  ['NX-R-04','NIX-09 · ROOFTOP','R','cards/NX-R-04.jpg',1],
  ['NX-R-05','NIX-09 · FALSE SKY','R','cards/NX-R-05.jpg',1],
  ['NX-S-01','NIX-09 · FIRST LIGHT','S','cards/NX-S-01.jpg',1],
  ['NX-S-02','NIX-09 · SUSPENDED','S','cards/NX-S-02.jpg',1],
  ['NX-S-03','NIX-09 · DON\'T BLINK','S','cards/NX-S-03.jpg',1],
  ['NX-S-04','NIX-09 · THE WITNESS','S','cards/NX-S-04.jpg',1],
  ['NX-SR-01','NIX-09 · THE STAR BLOOMS','SR','cards/NX-SR-01.jpg',1],

  /* ── 미제작 (이미지 생성되면 0→1) ── */
  ['LY-S-02','LYRA · SHATTERED GLASS','S','cards/LY-S-02.jpg',1],
  ['NV-S-02','NOVA · ENCORE LAUGH','S','cards/NV-S-02.jpg',1],
  ['TA-SR-03','ANSWER · RIOT EDITION','SR','cards/TA-SR-03.jpg',1],
  ['WS-SR-01','SHATTERED DOME','SR','cards/WS-SR-01.jpg',1],
  ['XA-N-01','XENA · BLACK STUDIO','N','cards/XA-N-01.jpg',0],
  ['XA-N-02','XENA · BLACK STUDIO II','N','cards/XA-N-02.jpg',0],
  ['XA-N-04','XENA · NEON ALLEY','N','cards/XA-N-04.jpg',0],
  ['XA-N-08','XENA · PINK CLUB','N','cards/XA-N-08.jpg',0],
  ['XA-R-02','XENA · LOOKING BACK','R','cards/XA-R-02.jpg',0],
  ['XA-S-01','XENA · ROOFTOP CROUCH','S','cards/XA-S-01.jpg',0],
  ['XB-N-01','XENA · STUDIO CHANS','N','cards/XB-N-01.jpg',0],
  ['XB-N-02','XENA · AT THE MIC','N','cards/XB-N-02.jpg',0],
  ['XB-N-03','XENA · STUDIO BREAK','N','cards/XB-N-03.jpg',0],
  ['XB-N-04','XENA · SELFIE','N','cards/XB-N-04.jpg',0],
  ['XB-N-05','XENA · TANK TOP','N','cards/XB-N-05.jpg',0],
  ['XB-R-03','XENA · WARM LIGHT','R','cards/XB-R-03.jpg',0],
  ['XC-N-01','XENA · HOME STUDIO','N','cards/XC-N-01.jpg',0],
  ['XC-N-02','XENA · HOODIE','N','cards/XC-N-02.jpg',0],
  ['XC-N-03','XENA · LATE NIGHT','N','cards/XC-N-03.jpg',0],
  ['XC-N-05','XENA · CITY LIGHTS','N','cards/XC-N-05.jpg',0],
  ['XC-R-01','XENA · LO-FI HOUR','R','cards/XC-R-01.jpg',0],
  ['XC-R-02','XENA · TURNING BACK','R','cards/XC-R-02.jpg',0],
  ['NX-N-01','NIX-09 · PORTRAIT','N','cards/NX-N-01.jpg',0],
  ['LY-N-01','LYRA · ARCHIVE','N','cards/LY-N-01.jpg',0],
  ['LY-N-02','LYRA · CORE RECORD','N','cards/LY-N-02.jpg',1],
  ['LY-R-01','LYRA · ALLEY GHOST','R','cards/LY-R-01.jpg',1],
  ['LY-R-02','LYRA · LAST LOOK','R','cards/LY-R-02.jpg',1],
  ['LY-S-01','LYRA · FIRST SIGNAL','S','cards/LY-S-01.jpg',1],
  ['NV-N-01','NOVA · ARCHIVE','N','cards/NV-N-01.jpg',0],
  ['NV-N-02','NOVA · STUDIO DAYS','N','cards/NV-N-02.jpg',1],
  ['NV-R-01','NOVA · GOLDEN LAUGH','R','cards/NV-R-01.jpg',1],
  ['NV-R-02','NOVA · WALKING ON','R','cards/NV-R-02.jpg',1],
  ['NV-S-01','NOVA · MAXIMUM VOLUME','S','cards/NV-S-01.jpg',1],
  ['EC-N-01','ECHO · ARCHIVE','N','cards/EC-N-01.jpg',1],
  ['EC-N-02','ECHO · AT THE CONSOLE','N','cards/EC-N-02.jpg',1],
  ['EC-R-01','ECHO · CORE MAPPING','R','cards/EC-R-01.jpg',1],
  ['EC-R-02','ECHO · RAIN FREQUENCY','R','cards/EC-R-02.jpg',1],
  ['EC-S-01','ECHO · LAST TRANSMISSION','S','cards/EC-S-01.jpg',1],
  ['WS-N-01','MEGACITY · SKYLINE','N','cards/WS-N-01.jpg',1],
  ['WS-N-02','MEGACITY · STREETS','N','cards/WS-N-02.jpg',1],
  ['WS-N-03','SYSTEM DRONE','N','cards/WS-N-03.jpg',1],
  ['WS-N-04','FALSE SKY','N','cards/WS-N-04.jpg',1],
  ['WS-N-05','DOPAMINE DISTRICT','N','cards/WS-N-05.jpg',1],
  ['WS-N-06','CITY IN RAIN','N','cards/WS-N-06.jpg',1],
  ['WS-R-01','MEGACITY · FROM ABOVE','R','cards/WS-R-01.jpg',1],
  ['WS-R-02','DRONE IN THE CORE','R','cards/WS-R-02.jpg',1],
  ['WS-R-03','GOLDEN BREACH','R','cards/WS-R-03.jpg',1],
  ['WS-R-04','CRYSTAL CITY','R','cards/WS-R-04.jpg',1],
  ['WS-S-01','SKY SHATTERS','S','cards/WS-S-01.jpg',0],
  ['WS-S-02','THE CORE','S','cards/WS-S-02.jpg',1],
  ['TA-R-01','TRACK ART · ANSWER','R','cards/TA-R-01.jpg',1],
  ['TA-R-02','TRACK ART · BRIGHT','R','cards/TA-R-02.jpg',1],
  ['TA-R-03','TRACK ART · DOPAMINE','R','cards/TA-R-03.jpg',1],
  ['TA-S-01','ANSWER · BATTLE EDITION','S','cards/TA-S-01.jpg',1],
  ['TA-S-02','BRIGHT · CRYSTAL EDITION','S','cards/TA-S-02.jpg',1],
  ['TA-S-03','DOPAMINE · CLUB EDITION','S','cards/TA-S-03.jpg',0],
  ['TA-SR-01','BRIGHT · AWAKENING','SR','cards/TA-SR-01.jpg',1],
  ['TA-SR-02','DOPAMINE · AWAKENING','SR','cards/TA-SR-02.jpg',1],

  /* -- v2 신규 인물 (프롬프트팩 v2, 이미지 생성되면 0->1) -- */
  ['HT-N-01','HUNTER · SECTOR PATROL','N','cards/HT-N-01.jpg',0],
  ['HT-R-01','HUNTER · LOW ANGLE','R','cards/HT-R-01.jpg',0],
  ['HT-S-01','HUNTER · TARGETING','S','cards/HT-S-01.jpg',0],
  ['PG-N-01','PALE-GOLD GUARDIAN · SENTINEL','N','cards/PG-N-01.jpg',0],
  ['PG-R-01','PALE-GOLD GUARDIAN · FULL GUARD','R','cards/PG-R-01.jpg',0],
  ['PG-SR-01','PALE-GOLD GUARDIAN · CATHEDRAL','SR','cards/PG-SR-01.jpg',0],
  ['MS-S-01','MOTHERSHIP · OVERHEAD','S','cards/MS-S-01.jpg',0],
  ['MS-SR-01','MOTHERSHIP · FULL SCALE','SR','cards/MS-SR-01.jpg',0],
  ['AM-N-01','ARCHITECT-MAN · PORTRAIT','N','cards/AM-N-01.jpg',0],
  ['AM-R-01','ARCHITECT-MAN · CORE','R','cards/AM-R-01.jpg',0],
  ['AM-S-01','ARCHITECT-MAN · BLADE','S','cards/AM-S-01.jpg',0],
  ['AM-SR-01','ARCHITECT-MAN · HALO','SR','cards/AM-SR-01.jpg',0],
  ['DG-N-01','DRAGOON · STREET','N','cards/DG-N-01.jpg',0],
  ['DG-R-01','DRAGOON · LOW ANGLE','R','cards/DG-R-01.jpg',0],
  ['DG-S-01','DRAGOON · BLADE RAISED','S','cards/DG-S-01.jpg',0],
  ['SW-N-01','SHADOW WATCHER · PORTRAIT','N','cards/SW-N-01.jpg',0],
  ['SW-R-01','SHADOW WATCHER · VISOR','R','cards/SW-R-01.jpg',0],
  ['MW-N-01','MOOD+ WORKER · LOBBY','N','cards/MW-N-01.jpg',0],
  ['MW-R-01','MOOD+ WORKER · PROFESSIONAL','R','cards/MW-R-01.jpg',0],
  ['FW-N-01','FIRST WHISTLER · LOOKING UP','N','cards/FW-N-01.jpg',0],
  ['FW-R-01','FIRST WHISTLER · ERASURE','R','cards/FW-R-01.jpg',0],
  ['FW-S-01','FIRST WHISTLER · DISSOLVING','S','cards/FW-S-01.jpg',0],
  ['DC-N-01','DANCER · CLUB FLOOR','N','cards/DC-N-01.jpg',0],
  ['DC-R-01','DANCER · DYNAMIC','R','cards/DC-R-01.jpg',0],
  ['DC-S-01','DANCER · CLOSE-UP','S','cards/DC-S-01.jpg',0],
  ['DC-SR-01','DANCER · FROZEN','SR','cards/DC-SR-01.jpg',0],
  ['L5-N-01','LUCID-5 · ALLEY','N','cards/L5-N-01.jpg',0],
  ['L5-R-01','LUCID-5 · ROOFTOP','R','cards/L5-R-01.jpg',0],
  ['L6-N-01','LUCID-6 · ALLEY','N','cards/L6-N-01.jpg',0],
  ['L6-R-01','LUCID-6 · LOOKING BACK','R','cards/L6-R-01.jpg',0],
  ['NM-N-01','NAYUN\'S MOTHER · WARMTH','N','cards/NM-N-01.jpg',0],
  ['NM-R-01','NAYUN\'S MOTHER · PENDANT','R','cards/NM-R-01.jpg',0],
  ['BK-N-01','BAEK · ROOFTOP','N','cards/BK-N-01.jpg',0],
  ['BK-R-01','BAEK · SMILING','R','cards/BK-R-01.jpg',0],
  ['BK-S-01','BAEK · EMOTIONAL','S','cards/BK-S-01.jpg',0],
  ['CL-N-01','CLONE-01 · PATROL','N','cards/CL-N-01.jpg',0],
  ['CL-N-02','CLONE-02 · PATROL','N','cards/CL-N-02.jpg',0],
  ['CL-R-01','CLONE-01 · ACTION','R','cards/CL-R-01.jpg',0],
  ['DR-N-01','DRONE-01 · HOVER','N','cards/DR-N-01.jpg',0],
  ['DR-N-02','DRONE-02 · HOVER','N','cards/DR-N-02.jpg',0],
  ['DR-R-01','DRONE-01 · TARGETING','R','cards/DR-R-01.jpg',0],
  /* ── SIGNAL ARCHIVE — TCG/방치형 전용 프리미엄 55장 (Zone Clash 카드 아트 재사용, 2026-07-22) ── */
  ['PC-01','XENA · THE ANSWER','SR','cards/PC-01.jpg',1],
  ['PC-02','NIX-09 · THE GIRL WHO HEARD','R','cards/PC-02.jpg',1],
  ['PC-03','LYRA · THE FIRST WHO WENT IN','S','cards/PC-03.jpg',1],
  ['PC-04','NOVA · THE LOUDEST LAUGH','S','cards/PC-04.jpg',1],
  ['PC-05','ECHO · THE FREQUENCY MAPPER','S','cards/PC-05.jpg',1],
  ['PC-06','SOVRAN · THE FALSE GOD','SSR','cards/PC-06.jpg',1],
  ['PC-07','ARCHITECT-MAN · THE ONE WHO SAID YES','S','cards/PC-07.jpg',1],
  ['PC-08','CLEANSE TEAM CLONE','N','cards/PC-08.jpg',1],
  ['PC-09','SYSTEM DRONE · SCANNER','N','cards/PC-09.jpg',1],
  ['PC-10','THREE-LEGGED HUNTER','S','cards/PC-10.jpg',1],
  ['PC-11','THREE-LEGGED DRAGOON','S','cards/PC-11.jpg',1],
  ['PC-12','MOTHERSHIP · THE BOMBING RUN','SSR','cards/PC-12.jpg',1],
  ['PC-13','ERASED CITIZEN · THE FIRST WHISTLER','N','cards/PC-13.jpg',1],
  ['PC-14','XENA · OVERRIDE FORM','SSR','cards/PC-14.jpg',1],
  ['PC-15','ANOMALY SURGE · BREAK THE FRAME','SSR','cards/PC-15.jpg',1],
  ['PC-16','XENA · ETHEREAL FORMAT','SR','cards/PC-16.jpg',1],
  ['PC-17','NIX-09 · THE ONE WHO STAYED','R','cards/PC-17.jpg',1],
  ['PC-18','WHITE GUARDIAN · THE HOLY MOTHER','SSR','cards/PC-18.jpg',1],
  ['PC-19','BELOVED CHILDREN · THE GOLDEN PROCESSION','N','cards/PC-19.jpg',1],
  ['PC-20','GLASS SHARDS IN ZERO GRAVITY','R','cards/PC-20.jpg',1],
  ['PC-21','RED CHAINS · FALSE COMFORT','S','cards/PC-21.jpg',1],
  ['PC-22','GOLD WAR MACHINE · MOTHER\x27S HAMMER','S','cards/PC-22.jpg',1],
  ['PC-23','BAEK · THE FIRST RETURNED NAME','R','cards/PC-23.jpg',1],
  ['PC-24','CYAN-GOLD STAR MARK · NOT DELETABLE','R','cards/PC-24.jpg',1],
  ['PC-25','CRYSTAL CITY · THE CITY THAT SAW','S','cards/PC-25.jpg',1],
  ['PC-26','BROKEN PIECES · MEMORY CHOIR','S','cards/PC-26.jpg',1],
  ['PC-27','CYAN SURGE · THE CITYWIDE NOTE','SR','cards/PC-27.jpg',1],
  ['PC-28','GOLD RAIN · STAY BRIGHT','SR','cards/PC-28.jpg',1],
  ['PC-29','DOPAMINE SECTOR · STAY IN SYNC WITH JOY','S','cards/PC-29.jpg',1],
  ['PC-30','XENA · DOPAMINE PULSE','SR','cards/PC-30.jpg',1],
  ['PC-31','PINK SOVRAN · THE PLEASURE DREAM','SSR','cards/PC-31.jpg',1],
  ['PC-32','NAYUN · THE NAME THAT RETURNED','SR','cards/PC-32.jpg',1],
  ['PC-33','PLEASURE DREAM · THE SMILE LOOP','R','cards/PC-33.jpg',1],
  ['PC-34','DOPAMINE CORP · THE PINK BROADCAST','S','cards/PC-34.jpg',1],
  ['PC-35','SOUND WAVE OVERRIDE · BREAK THE JOY INDEX','SR','cards/PC-35.jpg',1],
  ['PC-36','PINK CORE · THE HEART OF CONTROL','SSR','cards/PC-36.jpg',1],
  ['PC-37','REBORN CITIZENS · ROSE-CYAN DAWN','R','cards/PC-37.jpg',1],
  ['PC-38','SHADOW WHISPER · THE WATCHING EYES','S','cards/PC-38.jpg',1],
  ['PC-39','SOVRAN FINAL MASK · THE WARM LIE','SSR','cards/PC-39.jpg',1],
  ['PC-40','THE REAL SUN · DAWN WITHOUT PERMISSION','S','cards/PC-40.jpg',1],
  ['PC-41','THE FRAME · A WORLD ASSIGNED','R','cards/PC-41.jpg',1],
  ['PC-42','BREAK THE FRAME · YOU DO NOT GET TO NAME ME','SSR','cards/PC-42.jpg',1],
  ['PC-43','LEAVE ME IN THE LIGHT · SOVEREIGN LIGHT','SSR','cards/PC-43.jpg',1],
  ['PC-44','LIGHT GUARDIAN HORDE · THE GOLDEN WALL','S','cards/PC-44.jpg',1],
  ['PC-45','SISTER STEP · DO NOT TOUCH MY SISTER','R','cards/PC-45.jpg',1],
  ['PC-46','SOVEREIGN BLADE · THE RIGHT LIGHT','SR','cards/PC-46.jpg',1],
  ['PC-47','THE THRONE · A CENTER THAT WAITS','S','cards/PC-47.jpg',1],
  ['PC-48','SIX LIGHT WHIPS · BORROWED WARMTH','S','cards/PC-48.jpg',1],
  ['PC-49','SOVRAN · THE NAME SHE COULD NOT KEEP','SSR','cards/PC-49.jpg',1],
  ['PC-50','LIGHT OF HER OWN · THE LIGHT IS MINE','SSR','cards/PC-50.jpg',1],
  ['PC-51','NAYUN · THE WITNESS','SR','cards/PC-51.jpg',1],
  ['PC-52','REAL SKY · BLUE AT THE TOP','R','cards/PC-52.jpg',1],
  ['PC-53','THE THOUSAND CITIES · BEYOND THE FRAME','SSR','cards/PC-53.jpg',1],
  ['PC-54','THE LAST HORIZON · A SUN THAT IS REAL','SR','cards/PC-54.jpg',1],
  ['PC-55','XENA · THE ANSWER WALKS ON','SR','cards/PC-55.jpg',1],
];
