/* ZENA CARDS — 카드 데이터
 * 새 카드 추가법:
 *  1) 생성한 이미지를 이 폴더의 cards/ 에 "카드ID.webp" 파일명으로 넣는다 (예: cards/XA-N-01.webp)
 *  2) 아래 목록에서 해당 행의 마지막 숫자를 0 → 1 로 바꾼다 (1 = 게임에 등장)
 * 형식: [카드ID, 표시이름, 등급(N/R/S/SR/SSR), 이미지경로, 사용가능(1/0)]
 */
window.ZENA_CARD_DEFS = [
  /* ── GALLERY EDITION — 기존 화보 30장 (즉시 사용) ── */
  ['GA-AN-01','ANSWER · GALLERY #01','N','../../images/gallery/answer-1.jpg',1],
  ['GA-AN-02','ANSWER · GALLERY #02','N','../../images/gallery/answer-2.jpg',1],
  ['GA-AN-03','ANSWER · GALLERY #03','N','../../images/gallery/answer-3.jpg',1],
  ['GA-AN-04','ANSWER · GALLERY #04','N','../../images/gallery/answer-4.jpg',1],
  ['GA-AN-05','ANSWER · GALLERY #05','N','../../images/gallery/answer-5.jpg',1],
  ['GA-AN-06','ANSWER · GALLERY #06','R','../../images/gallery/answer-6.jpg',1],
  ['GA-AN-07','ANSWER · GALLERY #07','R','../../images/gallery/answer-7.jpg',1],
  ['GA-AN-08','ANSWER · GALLERY #08','R','../../images/gallery/answer-8.jpg',1],
  ['GA-AN-09','ANSWER · GALLERY #09','S','../../images/gallery/answer-9.jpg',1],
  ['GA-AN-10','ANSWER · GALLERY #10','S','../../images/gallery/answer-10.jpg',1],
  ['GA-BR-01','BRIGHT · GALLERY #01','N','../../images/gallery/bright-1.jpg',1],
  ['GA-BR-02','BRIGHT · GALLERY #02','N','../../images/gallery/bright-2.jpg',1],
  ['GA-BR-03','BRIGHT · GALLERY #03','N','../../images/gallery/bright-3.jpg',1],
  ['GA-BR-04','BRIGHT · GALLERY #04','N','../../images/gallery/bright-4.jpg',1],
  ['GA-BR-05','BRIGHT · GALLERY #05','N','../../images/gallery/bright-5.jpg',1],
  ['GA-BR-06','BRIGHT · GALLERY #06','R','../../images/gallery/bright-6.jpg',1],
  ['GA-BR-07','BRIGHT · GALLERY #07','R','../../images/gallery/bright-7.jpg',1],
  ['GA-BR-08','BRIGHT · GALLERY #08','R','../../images/gallery/bright-8.jpg',1],
  ['GA-BR-09','BRIGHT · GALLERY #09','S','../../images/gallery/bright-9.jpg',1],
  ['GA-BR-10','BRIGHT · GALLERY #10','S','../../images/gallery/bright-10.jpg',1],
  ['GA-DP-01','DOPAMINE · GALLERY #01','N','../../images/gallery/dopamine-1.jpg',1],
  ['GA-DP-02','DOPAMINE · GALLERY #02','N','../../images/gallery/dopamine-2.jpg',1],
  ['GA-DP-03','DOPAMINE · GALLERY #03','N','../../images/gallery/dopamine-3.jpg',1],
  ['GA-DP-04','DOPAMINE · GALLERY #04','N','../../images/gallery/dopamine-4.jpg',1],
  ['GA-DP-05','DOPAMINE · GALLERY #05','N','../../images/gallery/dopamine-5.jpg',1],
  ['GA-DP-06','DOPAMINE · GALLERY #06','R','../../images/gallery/dopamine-6.jpg',1],
  ['GA-DP-07','DOPAMINE · GALLERY #07','R','../../images/gallery/dopamine-7.jpg',1],
  ['GA-DP-08','DOPAMINE · GALLERY #08','R','../../images/gallery/dopamine-8.jpg',1],
  ['GA-DP-09','DOPAMINE · GALLERY #09','S','../../images/gallery/dopamine-9.jpg',1],
  ['GA-DP-10','DOPAMINE · GALLERY #10','S','../../images/gallery/dopamine-10.jpg',1],

  /* ── 1ST EDITION — ChatGPT 생성 카드 (사진 도착 시 0→1) ── */
  /* XENA-A 무대/화보 */
  ['XA-N-01','XENA · BLACK STUDIO','N','cards/XA-N-01.webp',0],
  ['XA-N-02','XENA · BLACK STUDIO II','N','cards/XA-N-02.webp',0],
  ['XA-N-03','XENA · CLOSE-UP','N','cards/XA-N-03.webp',0],
  ['XA-N-04','XENA · NEON ALLEY','N','cards/XA-N-04.webp',0],
  ['XA-N-05','XENA · NEON ALLEY II','N','cards/XA-N-05.webp',0],
  ['XA-N-06','XENA · ROOFTOP','N','cards/XA-N-06.webp',0],
  ['XA-N-07','XENA · GOLDEN SKY','N','cards/XA-N-07.webp',0],
  ['XA-N-08','XENA · PINK CLUB','N','cards/XA-N-08.webp',0],
  ['XA-N-09','XENA · RAIN GLASS','N','cards/XA-N-09.webp',0],
  ['XA-N-10','XENA · ON STAGE','N','cards/XA-N-10.webp',0],
  ['XA-R-01','XENA · ALLEY LOW ANGLE','R','cards/XA-R-01.webp',0],
  ['XA-R-02','XENA · LOOKING BACK','R','cards/XA-R-02.webp',0],
  ['XA-R-03','XENA · ROOFTOP WIND','R','cards/XA-R-03.webp',0],
  ['XA-R-04','XENA · GOLDEN HOUR','R','cards/XA-R-04.webp',0],
  ['XA-R-05','XENA · CRYSTAL CITY','R','cards/XA-R-05.webp',0],
  ['XA-R-06','XENA · CLUB DANCE','R','cards/XA-R-06.webp',0],
  ['XA-R-07','XENA · SERVER CORE','R','cards/XA-R-07.webp',0],
  ['XA-R-08','XENA · RAIN SILHOUETTE','R','cards/XA-R-08.webp',0],
  ['XA-R-09','XENA · STAGE DANCE','R','cards/XA-R-09.webp',0],
  ['XA-S-01','XENA · ROOFTOP CROUCH','S','cards/XA-S-01.webp',0],
  ['XA-S-02','XENA · GOLDEN ASCENT','S','cards/XA-S-02.webp',0],
  ['XA-S-03','XENA · CRYSTAL DANCE','S','cards/XA-S-03.webp',0],
  ['XA-S-04','XENA · NEON GAZE','S','cards/XA-S-04.webp',0],
  ['XA-S-05','XENA · STAGE STORM','S','cards/XA-S-05.webp',0],
  ['XA-S-06','XENA · ZERO GRAVITY','S','cards/XA-S-06.webp',0],
  ['XA-SR-01','XENA · CYAN BLADE','SR','cards/XA-SR-01.webp',0],
  ['XA-SR-02','XENA · ROOFTOP HUNTER','SR','cards/XA-SR-02.webp',0],
  ['XA-SR-03','XENA · CORE WALKER','SR','cards/XA-SR-03.webp',0],
  ['XA-SR-04','XENA · SHATTERED TIME','SR','cards/XA-SR-04.webp',0],
  ['XA-SSR-01','XENA · OVERRIDE','SSR','cards/XA-SSR-01.webp',0],
  /* XENA-B 스튜디오 */
  ['XB-N-01','XENA · STUDIO CHANS','N','cards/XB-N-01.webp',0],
  ['XB-N-02','XENA · AT THE MIC','N','cards/XB-N-02.webp',0],
  ['XB-N-03','XENA · STUDIO BREAK','N','cards/XB-N-03.webp',0],
  ['XB-N-04','XENA · SELFIE','N','cards/XB-N-04.webp',0],
  ['XB-N-05','XENA · TANK TOP','N','cards/XB-N-05.webp',0],
  ['XB-R-01','XENA · OVER SHOULDER','R','cards/XB-R-01.webp',0],
  ['XB-R-02','XENA · CONSOLE SEAT','R','cards/XB-R-02.webp',0],
  ['XB-R-03','XENA · WARM LIGHT','R','cards/XB-R-03.webp',0],
  ['XB-S-01','XENA · STUDIO GROOVE','S','cards/XB-S-01.webp',0],
  ['XB-S-02','XENA · SOFT SMILE','S','cards/XB-S-02.webp',0],
  /* XENA-C 홈 프로듀서 */
  ['XC-N-01','XENA · HOME STUDIO','N','cards/XC-N-01.webp',0],
  ['XC-N-02','XENA · HOODIE','N','cards/XC-N-02.webp',0],
  ['XC-N-03','XENA · LATE NIGHT','N','cards/XC-N-03.webp',0],
  ['XC-N-04','XENA · WINDOW RAIN','N','cards/XC-N-04.webp',0],
  ['XC-N-05','XENA · CITY LIGHTS','N','cards/XC-N-05.webp',0],
  ['XC-R-01','XENA · LO-FI HOUR','R','cards/XC-R-01.webp',0],
  ['XC-R-02','XENA · TURNING BACK','R','cards/XC-R-02.webp',0],
  ['XC-R-03','XENA · RAIN PROFILE','R','cards/XC-R-03.webp',0],
  ['XC-S-01','XENA · QUIET DAWN','S','cards/XC-S-01.webp',0],
  ['XC-S-02','XENA · GLASS REFLECTION','S','cards/XC-S-02.webp',0],
  /* NIX-09 */
  ['NX-N-01','NIX-09 · PORTRAIT','N','cards/NX-N-01.webp',0],
  ['NX-N-02','NIX-09 · ALLEY','N','cards/NX-N-02.webp',0],
  ['NX-N-03','NIX-09 · SITTING','N','cards/NX-N-03.webp',0],
  ['NX-N-04','NIX-09 · RAIN WINDOW','N','cards/NX-N-04.webp',0],
  ['NX-N-05','NIX-09 · MEGACITY','N','cards/NX-N-05.webp',0],
  ['NX-N-06','NIX-09 · GOLDEN LIGHT','N','cards/NX-N-06.webp',0],
  ['NX-R-01','NIX-09 · LOOKING BACK','R','cards/NX-R-01.webp',0],
  ['NX-R-02','NIX-09 · RAIN PROFILE','R','cards/NX-R-02.webp',0],
  ['NX-R-03','NIX-09 · GOLDEN GAZE','R','cards/NX-R-03.webp',0],
  ['NX-R-04','NIX-09 · ROOFTOP','R','cards/NX-R-04.webp',0],
  ['NX-R-05','NIX-09 · FALSE SKY','R','cards/NX-R-05.webp',0],
  ['NX-S-01','NIX-09 · FIRST LIGHT','S','cards/NX-S-01.webp',0],
  ['NX-S-02','NIX-09 · SUSPENDED','S','cards/NX-S-02.webp',0],
  ['NX-S-03','NIX-09 · DON\'T BLINK','S','cards/NX-S-03.webp',0],
  ['NX-SR-01','NIX-09 · THE STAR BLOOMS','SR','cards/NX-SR-01.webp',0],
  /* LYRA / NOVA / ECHO */
  ['LY-N-01','LYRA · ARCHIVE','N','cards/LY-N-01.webp',0],
  ['LY-N-02','LYRA · CORE RECORD','N','cards/LY-N-02.webp',0],
  ['LY-R-01','LYRA · ALLEY GHOST','R','cards/LY-R-01.webp',0],
  ['LY-R-02','LYRA · LAST LOOK','R','cards/LY-R-02.webp',0],
  ['LY-S-01','LYRA · FIRST SIGNAL','S','cards/LY-S-01.webp',0],
  ['NV-N-01','NOVA · ARCHIVE','N','cards/NV-N-01.webp',0],
  ['NV-N-02','NOVA · STUDIO DAYS','N','cards/NV-N-02.webp',0],
  ['NV-R-01','NOVA · GOLDEN LAUGH','R','cards/NV-R-01.webp',0],
  ['NV-R-02','NOVA · WALKING ON','R','cards/NV-R-02.webp',0],
  ['NV-S-01','NOVA · MAXIMUM VOLUME','S','cards/NV-S-01.webp',0],
  ['EC-N-01','ECHO · ARCHIVE','N','cards/EC-N-01.webp',0],
  ['EC-N-02','ECHO · AT THE CONSOLE','N','cards/EC-N-02.webp',0],
  ['EC-R-01','ECHO · CORE MAPPING','R','cards/EC-R-01.webp',0],
  ['EC-R-02','ECHO · RAIN FREQUENCY','R','cards/EC-R-02.webp',0],
  ['EC-S-01','ECHO · LAST TRANSMISSION','S','cards/EC-S-01.webp',0],
  /* 세계관 씬 */
  ['WS-N-01','MEGACITY · SKYLINE','N','cards/WS-N-01.webp',0],
  ['WS-N-02','MEGACITY · STREETS','N','cards/WS-N-02.webp',0],
  ['WS-N-03','SYSTEM DRONE','N','cards/WS-N-03.webp',0],
  ['WS-N-04','FALSE SKY','N','cards/WS-N-04.webp',0],
  ['WS-N-05','DOPAMINE DISTRICT','N','cards/WS-N-05.webp',0],
  ['WS-N-06','CITY IN RAIN','N','cards/WS-N-06.webp',0],
  ['WS-R-01','MEGACITY · FROM ABOVE','R','cards/WS-R-01.webp',0],
  ['WS-R-02','DRONE IN THE CORE','R','cards/WS-R-02.webp',0],
  ['WS-R-03','GOLDEN BREACH','R','cards/WS-R-03.webp',0],
  ['WS-R-04','CRYSTAL CITY','R','cards/WS-R-04.webp',0],
  ['WS-S-01','SKY SHATTERS','S','cards/WS-S-01.webp',0],
  ['WS-S-02','THE CORE','S','cards/WS-S-02.webp',0],
  /* 트랙 아트 변주 */
  ['TA-R-01','TRACK ART · ANSWER','R','cards/TA-R-01.webp',0],
  ['TA-R-02','TRACK ART · BRIGHT','R','cards/TA-R-02.webp',0],
  ['TA-R-03','TRACK ART · DOPAMINE','R','cards/TA-R-03.webp',0],
  ['TA-S-01','ANSWER · BATTLE EDITION','S','cards/TA-S-01.webp',0],
  ['TA-S-02','BRIGHT · CRYSTAL EDITION','S','cards/TA-S-02.webp',0],
  ['TA-S-03','DOPAMINE · CLUB EDITION','S','cards/TA-S-03.webp',0],
  ['TA-SR-01','BRIGHT · AWAKENING','SR','cards/TA-SR-01.webp',0],
  ['TA-SR-02','DOPAMINE · AWAKENING','SR','cards/TA-SR-02.webp',0]
];
