(function(){
  "use strict";
  const cards=[{id:"guard-nix",name:"NIX-09",cost:1,power:1},{id:"guard-echo",name:"ECHO",cost:2,power:2},{id:"guard-xena",name:"XENA",cost:3,power:4}];
  const ADMIN_UID="PiegXmg9KjNJS9JDS3piP0agUB02";
  let adminAllowed=false;
  const state={phase:"intro",stageHp:10,signal:3,maxSignal:10,elapsed:0,duration:60,selected:"",cards:[],enemies:[],kills:0,timer:null};
  const $=s=>document.querySelector(s);
  function status(v,alert){$("#status").textContent=v;$("#status").style.color=alert?"#ff657e":"#ffd875";}
  function render(){
    $("#intro-panel").hidden=state.phase!=="intro";$("#game-panel").hidden=!['playing','paused'].includes(state.phase);$("#result-panel").hidden=!['win','lose'].includes(state.phase);
    $("#stage-hp").textContent=`${state.stageHp} / 10`;$("#signal").textContent=`${state.signal} / ${state.maxSignal}`;$("#time").textContent=`${Math.max(0,state.duration-state.elapsed)}s`;
    const board=$("#board");board.innerHTML="";
    for(let row=0;row<3;row++)for(let col=0;col<5;col++){const cell=document.createElement("button");cell.type="button";cell.className=`cell${col===0?" stage":""}${state.selected&&col>0&&!state.cards.some(c=>c.row===row&&c.col===col)?" target":""}`;cell.dataset.row=row;cell.dataset.col=col;if(col===0)cell.innerHTML='<span>STAGE</span>';const card=state.cards.find(c=>c.row===row&&c.col===col);const enemy=state.enemies.find(e=>e.row===row&&e.col===col);if(card)cell.innerHTML=`<span class="piece"><b>${card.name}</b><small>PWR ${card.power}</small></span>`;if(enemy)cell.innerHTML=`<span class="piece enemy"><img src="./assets/intruder.png" alt="" style="width:34px;height:34px;object-fit:cover;border-radius:8px;align-self:center"><b>INTRUDER</b><small>HP ${enemy.hp}</small></span>`;board.appendChild(cell)}
    $("#hand").innerHTML=cards.map(c=>{const disabled=state.signal<c.cost||state.cards.length>=12;return `<button class="hand-card${state.selected===c.id?" selected":""}" data-card="${c.id}" ${disabled?"disabled":""}><b>${c.name}</b><small>COST ${c.cost} · POWER ${c.power}</small></button>`}).join("");
  }
  function start(){if(!adminAllowed)return;state.phase="playing";state.stageHp=10;state.signal=3;state.elapsed=0;state.selected="";state.cards=[];state.enemies=[];state.kills=0;clearInterval(state.timer);state.timer=setInterval(tick,2000);window.XenaAudio?.sfx("btn_click");status("카드를 골라 빈 칸에 배치하세요.");render()}
  function place(row,col){if(!state.selected||col===0||state.cards.some(c=>c.row===row&&c.col===col))return;const c=cards.find(x=>x.id===state.selected),count=state.cards.filter(x=>x.id===c.id).length;if(state.signal<c.cost)return;state.signal-=c.cost;state.cards.push({name:c.name,power:c.power,row,col,id:`${c.id}-${Date.now()}-${count}`});state.selected="";window.XenaAudio?.sfx("tile_select");status("카드가 배치되었습니다.");render()}
  function tick(){if(state.phase!=="playing")return;state.elapsed+=2;state.signal=Math.min(state.maxSignal,state.signal+1);if(state.elapsed===50)window.XenaAudio?.sfx("time_warning");const row=Math.floor(Math.random()*3);state.enemies.push({row,col:4,hp:1,attack:1});for(const enemy of state.enemies){if(enemy.col>0)enemy.col-=1}for(const enemy of [...state.enemies]){const card=state.cards.find(c=>c.row===enemy.row&&c.col===enemy.col);if(card){window.XenaAudio?.sfx("stageguard_collision");enemy.hp-=card.power;card.power-=enemy.attack;if(enemy.hp<=0){state.enemies=state.enemies.filter(e=>e!==enemy);state.kills++}if(card.power<=0)state.cards=state.cards.filter(c=>c!==card)}else if(enemy.col===0){window.XenaAudio?.sfx("match_fail_a");state.stageHp--;state.enemies=state.enemies.filter(e=>e!==enemy)}}if(state.stageHp<=0)return finish("lose");if(state.elapsed>=state.duration)return finish("win");render()}
  function finish(p){clearInterval(state.timer);state.phase=p;window.XenaAudio?.sfx(p==="win"?"stage_clear_a":"match_fail_a");$("#result-kicker").textContent=p==="win"?"STAGE SECURED":"STAGE LOST";$("#result-title").textContent=p==="win"?"무대를 지켰습니다":"무대가 점령되었습니다";$("#result-copy").textContent=p==="win"?`60초 생존 · 격파 ${state.kills}기`:`무대 HP ${state.stageHp} · 격파 ${state.kills}기`;$("#result-score").textContent=String(state.kills*10+state.stageHp*5);render()}
  $("#start-button").addEventListener("click",start);$("#retry-button").addEventListener("click",start);$("#pause-button").addEventListener("click",()=>{if(state.phase==="playing"){state.phase="paused";clearInterval(state.timer);$("#pause-button").textContent="계속하기";status("일시정지되었습니다")}else if(state.phase==="paused"){state.phase="playing";state.timer=setInterval(tick,2000);$("#pause-button").textContent="일시정지";status("게임을 계속합니다.")}render()});$("#board").addEventListener("click",e=>{const c=e.target.closest("[data-row]");if(c)place(Number(c.dataset.row),Number(c.dataset.col))});$("#hand").addEventListener("click",e=>{const b=e.target.closest("[data-card]");if(!b)return;state.selected=state.selected===b.dataset.card?"":b.dataset.card;window.XenaAudio?.sfx("tile_select");render()});$("#language").addEventListener("click",()=>{document.documentElement.lang=document.documentElement.lang==="ko"?"en":"ko";});$("#sound").addEventListener("click",()=>document.body.classList.toggle("sound-muted"));if(window.XenaAudio)window.XenaAudio.init("stageguard");
  function enforceAdmin(){const identity=window.XenaIdentity?.getState?.();if(!identity?.signedIn)return;adminAllowed=identity.uid===ADMIN_UID;if(!adminAllowed){$("#intro-panel").innerHTML='<p class="eyebrow">PRIVATE PREVIEW</p><h1>STAGEGUARD <span>SOON</span></h1><p>현재는 관리자 테스트 전용입니다. 정식 공개 준비가 끝나면 모든 플레이어에게 공개됩니다.</p><a class="secondary" href="../">XENA GAMES로 돌아가기</a>';$("#result-panel").hidden=true;}}
  if(window.XenaIdentity)window.XenaIdentity.subscribe(enforceAdmin);enforceAdmin();render();
})();
